name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm -r lint || echo "no lint script"

      - name: Test
        run: pnpm -r test -- --ci --reporters=default

      - name: Build
        run: pnpm -r build || echo "no build script"

      - name: Archive backend dist (if any)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: apps/backend/dist
          if-no-files-found: ignore
