name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: |
          cd apps/frontend
          pnpm build

      - name: Build backend
        run: |
          cd apps/backend
          pnpm build

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t pluxuryv8/randarcmarket-backend:latest ./apps/backend
          docker build -t pluxuryv8/randarcmarket-frontend:latest ./apps/frontend
          docker push pluxuryv8/randarcmarket-backend:latest
          docker push pluxuryv8/randarcmarket-frontend:latest

      - name: Deploy to server
        if: success()
        run: |
          echo "Deployment completed successfully"
          # Здесь можно добавить команды для деплоя на ваш сервер
          # Например, через SSH или через Docker Compose
